version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo "ⓘ Installing dependencies"
      - curl -fsSL https://get.pnpm.io/install.sh | SHELL=`which bash` bash -
      - . ~/.bashrc
      - pnpm install
    finally:
      - echo "Finished Install stage!"
  pre-build:
    commands:
      - "cd "
  build:
    commands:
      - pnpm dlx turbo build
    finally:
      - echo "ⓘ Build Stage Complete"
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    api:
      files:
        - 'apps/api/**/*'
      name: api
      discard-paths: no
    web:
      files:
        - 'apps/web/**/*'
      base-directory: 'apps/web'
      discard-paths: no
      name: web