import type { Metadata } from "next";
import { Lora, DM_Mono, DM_Sans } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import footerLogo from '@/assets/images/logo/gradex-minified-solid.svg'
import Image from "next/image";
import Link from "next/link";
import GlobalToastRegion from "@/components/react-aria/GlobalToast";
import { Toaster } from 'react-hot-toast';


const serif = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora',
})
 
const sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans',
})

const mono = DM_Mono({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-mono',
})

export const metadata: Metadata = {
  title: "GradeX",
  description: "Generated by create next app",
  applicationName: "GradeX",
  authors: [
    {
      name: 'tortenworx',
      url: 'https://worx.torten.xyz'
    },
    {
      name: 'Torten Kiritsugu',
      url: 'https://torten.xyz'
    }
  ],
  category: "Education",
  keywords: ['grades', 'report cards', 'report card portal']
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body
          className={`${serif.variable} ${mono.variable} ${sans.variable} antialiased font-sans`}
        >
          {children}
          <footer className="bg-oct-darkgreen py-4 md:py-8 px-12 grid gap-4 md:grid-cols-3 text-gray-300 text-base">
            <div>
              <Image src={footerLogo} width={164} alt="GradeX" />
              <p className="mt-4">
                &copy; 2024 All rights reserved.
              </p>
              <p>
                GradeX is a capstone project made to fulfill the requirements of Practical Research 2 (SH004) and Inquiries, Investigations, and Immersions (SH007). For more details of our research paper, please visit the <Link href="/about" className="text-oct-yellow underline underline-offset-4">about page</Link>.
              </p>
            </div>
            <div className="flex flex-col">
              <h5 className="font-mono text-oct-yellow uppercase">Links</h5>
              <a href="https://olivarezcollegetagaytay.edu.ph" target="_blank">Website</a>
              <a href="https://facebook.com/OCTagaytayOfficial" target="_blank">Facebook</a>
              <a href="https://www.facebook.com/oct.shs/" target="_blank">SHS Facebook</a>
            </div>
            <div className="flex flex-col">
              <h5 className="text-oct-yellow uppercase font-mono">Services</h5>
              <a href="https://octiensys.com" target="_blank">Student Portal</a>
              <a href="https://119.93.245.104/iensys/" target="_blank">Faculty Portal</a>
              <a href="http://119.93.245.104:8080" target="_blank">eLibrary</a>
            </div>
          </footer>
          <Toaster position="bottom-right" />
        </body>
      </SessionProvider>
    </html>
  );
}
