import type { Metadata } from "next";
import { Lora, DM_Mono, DM_Sans } from "next/font/google";
import "./globals.css";

const serif = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lora',
})
 
const sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-sans',
})

const mono = DM_Mono({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-dm-mono',
})

export const metadata: Metadata = {
  title: "GradeX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${serif.variable} ${mono.variable} ${sans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
